### PR TITLE
Fixed angular version

### PR DESCRIPTION
**Pull request by Flowwwww**

### CODE REVIEW

**Comment by jacksonhart** [comment]
getting same error

**Comment by bergben** [comment]
@Flowwwww can you have a look into this?

**Comment by Flowwwww** [comment]
I'll take a look. Just give me some time...

**Comment by Flowwwww** [comment]
I didn't manage to make it work ... I corrected the mentionned error but i'm facing new issues 

ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve 'ng2-img-max' in '...'

If someone can help ...

**Comment by jacksonhart** [comment]
not sure what your changes were doing @Flowwwww i.e. with renaming the file but the original error seems to be because ng2-pica is using .ts files.

from an Angular dev (on the thread https://github.com/angular/angular-cli/issues/8284#issuecomment-341417325)
"You have TS files in your node_modules. This really goes against how libraries should be packaged: libraries should never ship their source .ts files."
I think the newer angular version is more strict with not allowing this.

@bergben is it possible to re-publish ng2-pica to get compiled .js files?

otherwise the same comment (search for the quote above) suggests that a workaround might be possible by adding files to the 'include' section of tsconfig

**Comment by bergben** [comment]
should be fixed with the most recent version now! :)

**Pull request merged**
