### PR TITLE
replaced exif-js with exifr

### PR DESCRIPTION
**Pull request by MikeKovarik**
in response to https://github.com/bergben/ng2-img-max/issues/41

### CODE REVIEW

**Comment by fgisslen** [comment]
@MikeKovarik hi I get this error ReferenceError: TextDecoder is not defined after the update to exifr.

**Comment by MikeKovarik** [comment]
Hi. what browser are you using?

**Comment by MikeKovarik** [comment]
Ok. so i noticed this module supports IE10+. I mistakenly assumed it supports only evergreens, but i was looking at ng2-pica where there's no mention of IE in the readme.

The fix is fortunately faily simple. All that's needed is simply replace plain import
```js
import * as exifr from 'exifr';
```
with legacy one (it includes shim for TextDecoder
```
import * as exifr from 'exifr/dist/core.legacy.umd.js';
```
I'll make PRs today

**Comment by bergben** [comment]
released 2.2.2 with new PRs

**Pull request merged**
